name: Docker Build and Push to Hub

on: [push]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Set date tag
        id: set_date_tag
        run: echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${DOCKER_USERNAME}/bswpyimagegeneratorapi:latest .
          docker tag ${DOCKER_USERNAME}/bswpyimagegeneratorapi:latest ${DOCKER_USERNAME}/bswpyimagegeneratorapi:${DATE_TAG}

      - name: Push Docker image to Hub
        run: |
          docker push ${DOCKER_USERNAME}/bswpyimagegeneratorapi:latest
          docker push ${DOCKER_USERNAME}/bswpyimagegeneratorapi:build${DATE_TAG}
